import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'

const inter = Inter({ subsets: ['latin'] })

// MongoDB ==> utils, api
// Redux =>  

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.red}>
                <h1>Hello</h1>
            </main>
        </>
    )
}

// Notes:
// - @reduxjs/toolkit : is the modern way of doing redux
// - redux-wrapper : to wrap all of the application with the store
// - redux-thunk : to allow async function
// - redux-persist : to store the information even the page was refresh (it is still can access the store and see the information)
